networks:
  evnet: {}

volumes:
  pg_catalog: {}
  pg_identity: {}
  pg_kong: {}

services:
  # -----------------------------
  # CATALOG DATABASE + API
  # -----------------------------
  catalog-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${CATALOG_DB_USER}
      POSTGRES_PASSWORD: ${CATALOG_DB_PASSWORD}
      POSTGRES_DB: ${CATALOG_DB_NAME}
    ports: ["5434:5432"]
    volumes:
      - pg_catalog:/var/lib/postgresql/data
    networks: [evnet]

  catalog-api:
    build:
      context: .
      dockerfile: src/catalog-service/Catalog.API/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: "Host=catalog-db;Port=5432;Database=${CATALOG_DB_NAME};Username=${CATALOG_DB_USER};Password=${CATALOG_DB_PASSWORD}"
    depends_on:
      - catalog-db
    ports:
      - "8102:8080"
    networks:
      evnet:
        aliases:
          - catalog-api
    restart: unless-stopped

  # -----------------------------
  # IDENTITY DATABASE + API
  # -----------------------------
  identity-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${IDENTITY_DB_USER}
      POSTGRES_PASSWORD: ${IDENTITY_DB_PASSWORD}
      POSTGRES_DB: ${IDENTITY_DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - pg_identity:/var/lib/postgresql/data
    networks: [evnet]

  identity-api:
    build:
      context: .
      dockerfile: src/identity-service/Identity.API/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: "Host=identity-db;Port=5432;Database=${IDENTITY_DB_NAME};Username=${IDENTITY_DB_USER};Password=${IDENTITY_DB_PASSWORD}"
    depends_on:
      - identity-db
    ports:
      - "8103:8080"
    networks:
      evnet:
        aliases:
          - identity-api
    restart: unless-stopped

  # -----------------------------
  # KONG DATABASE
  # -----------------------------
  kong-db:
    image: postgres:11
    container_name: kong-db
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    volumes:
      - pg_kong:/var/lib/postgresql/data
    networks: [evnet]
    ports:
      - "5436:5432"  # optional, connect if needed

  # -----------------------------
  # KONG GATEWAY (DB MODE)
  # -----------------------------
  kong:
    image: kong:3.7
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"  # Gateway
      - "8001:8001"  # Admin API
    depends_on:
      - kong-db
      - catalog-api
    networks:
      evnet:
        aliases:
          - kong
    restart: unless-stopped

  # -----------------------------
  # KONGA DASHBOARD
  # -----------------------------
  konga:
    image: pantsel/konga:latest
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      NODE_ENV: production
    networks:
      evnet:
        aliases:
          - konga
